1) Vytvořte pole 3x4 typu bool se všemi prvky True.
2) Vytvořte matici 5x5 kde jediné nenulová prvky jsou [1, 2, 3, 4] pod hlavní diagonálou (nápověda - podívejte se na nápovědu funkce diagflat).

In [29]:
import numpy as np

A = np.ones(shape=(3,4), dtype=bool)
print(A)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [52]:
B = np.diagflat([1, 2, 3, 4], -1)
print(B)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Z pole 8x8 samých nul vyvořte pomocí řezů co nejelegantnějším způsobem 8x8 matici, která vypadá jako šachovnice.

In [77]:
C = np.zeros((8,8))
for i in range(len(C)):
    if(i%2 == 0):C[i][0:8:2]= 1
    if(i%2 == 1):C[i][1:9:2]= 1
print(C)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


4) Pomocí np.random.randint vytvořte vektor dvouciferných kladných celých čísel. Poté pomocí indexu typu masky nahraďte liché hodnoty jejich opačnou hodnotou. Např. [11, 20, 42, 33] -> [-11, 20, 42, -33].

In [89]:
D = np.random.randint(10,99,(5))
print(D)
for i in range(len(D)):
    if(D[i]%2 == 1): D[i] *= -1
print(D)

[53 31 39 23 68]
[-53 -31 -39 -23  68]


5)

In [93]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
C = np.transpose(A*B)
D = np.transpose(A)* np.transpose(B)
print(C)
print("-----------------------------")
print(D)
print("-----------------------------")
print(C-D)

[[0.02682811 0.14633227 0.09524339]
 [0.0242823  0.08002354 0.63079964]
 [0.45251012 0.26280428 0.30670666]]
-----------------------------
[[0.02682811 0.14633227 0.09524339]
 [0.0242823  0.08002354 0.63079964]
 [0.45251012 0.26280428 0.30670666]]
-----------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Pro náhodné 1D vektory vypočítejte dyadický součin n*v 

In [38]:
import numpy as np

n = np.random.random(8)
v = np.random.random(8)
out = np.zeros([8,8])
for i in range(len(n)):
    for j in range(len(v)):
        out[i][j] = n[i] * v[j]

print((out - (np.outer(n,v)))) # vypočtený dekadický součin - np.outer(n,v) by se měl = 0


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


7) Vytvořte šachovnicovou matici pomocí tile.

In [40]:
n = 4 #velikost šachovnice, 4 == šachovnice
a = np.array([[1, 0], [0, 1]])
print(np.tile(a, (n, n)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Domácí Úkol

In [41]:
import numpy as np
import matplotlib as plt

def integer_spiral(n):
    A = np.zeros([n+2,n+2])
    pos_rows = n//2 +1
    pos_cols = n//2 +1
    i = 1

    A[pos_rows, pos_cols] = i
    i += 1
    pos_rows -= 1

    while(i <= n**2):
        A[pos_rows, pos_cols] = i
        i+=1
        if(A[pos_row - 1, pos_col] != 0 and A[pos_row, pos_col + 1] == 0):
            pos_cols += 1
        elif(A[pos_row, pos_col - 1] != 0):
            pos_row -= 1
        elif(A[pos_row + 1, pos_col] != 0):
            pos_col -= 1
        else:
            pos_row += 1

    return A[1:-1, 1:-1]

A = integer_spiral(7)
print(A)


SyntaxError: incomplete input (2324417572.py, line 4)